# Generated by Django 4.2.30 on 2026-05-30 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('read_time', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('rating', models.FloatField(default=4.0)),
                ('type', models.CharField(max_length=50)),
                ('placement_support', models.CharField(max_length=255)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('tools', models.JSONField(default=list)),
                ('skills_covered', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=4.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('placement_rate', models.IntegerField(default=85)),
                ('students_trained', models.IntegerField(default=0)),
                ('avg_package', models.CharField(max_length=50)),
                ('highest_package', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('fees_range', models.CharField(max_length=100)),
                ('locations', models.JSONField(default=list)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('hiring_partners', models.JSONField(default=list)),
                ('gallery', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_package', models.CharField(max_length=50)),
                ('avg_package', models.CharField(max_length=50)),
                ('students_placed', models.CharField(max_length=50)),
                ('active_partners', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_modules', to='api.course')),
            ],
            options={
                'ordering': ['module_number'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField()),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='api.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='api.course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='api.institute')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institutes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.institute'),
        ),
    ]
